# CI de Nível 02 - Disparo automático baseado na cron

# Nome do pipeline
name: 'Execução Automática'

# Regras de disparo (gatilhos ou triggers)
# Gatilho de execução automática = schedule

# a - minuto
# b - hora
# c - dia do mês
# d - mês
# e - dia da semana

# rodar o regressivo toda segunda-feira pela manhã
# 'cron'
# a b c d e
# 0 6 * * 1

on:
  schedule:
    # Executa o pipeline at 17:35 BRT on Saturday
    - cron: '35 20 * * 6'

# Trabalhos/tarefas dentro do pipeline = jobs
jobs:
  # Nome do trabalho
  e2e-tests:
    # Máquina onde o job será executado
    runs-on: ubuntu-latest

    # Passos do script do build
    steps:
      # Clone do projeto
      - uses: actions/checkout@v4

      # Instalação do node.js
      - uses: actions/setup-node@v4
        with:
          node-version: 22.x

      # Instalação do yarn
      - name: Instalando yarn
        run: npm install -g yarn

      # Instalação das dependências do projeto
      - name: Instalando dependências do projeto
        run: yarn

      # Instalação do Playwright
      - name: Instalando Playwright
        run: yarn playwright install
