# CI Nivel 08 - Disparo dos testes dentro do pipeline de dev

name: 'Execução Integrada'

on:
  workflow_dispatch:

jobs:
  inspecao:
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v4

      - name: Instalando dependências do projeto
        run: yarn

      - name: Checando padronização de código
        run: yarn lint

  unit-tests:
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v4

      - name: Instalando dependências do projeto
        run: yarn

      - name: Executando os Testes Unitários
        run: yarn test

    steps:
      - uses: actions/checkout@v4

      - uses: actions/setup-node@v4
        with:
          node-version: 22.x

      - name: Instalando dependências do projeto
        run: yarn

      - name: Instalando Playwright
        run: yarn playwright install

      - uses: actions/upload-artifact@v4
        if: ${{ !cancelled() }}
        with:
          name: Playwright Report File
          path: ./playwright-report

  deploy:
    runs-on: ubuntu-latest

    steps:
      - name: Simulando Deploy
        run: echo "Deploy realizado com sucesso!"
